// <auto-generated />
using System;
using Glinter.Modules.Experiences.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.Experiences.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExperiencesDbContext))]
    [Migration("20260629015545_AddSearchAndReportingIndexes")]
    partial class AddSearchAndReportingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adm3Gid")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PricePerPerson")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProviderProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Adm3Gid");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("ProviderProfileId", "CreatedAtUtc")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("Adm3Gid", "IsActive", "ApprovalStatus")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("CategoryId", "IsActive", "ApprovalStatus")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("IsActive", "ApprovalStatus", "CreatedAtUtc")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("ProviderProfileId", "Adm3Gid", "Title")
                        .IsUnique();

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BookedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartTimeUtc");

                    b.HasIndex("ExperienceId", "IsActive", "StartTimeUtc", "EndTimeUtc")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("experience_availability", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("Status");

                    b.HasIndex("TravelerProfileId");

                    b.HasIndex("AvailabilityId", "TravelerProfileId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.HasIndex("CreatedAtUtc", "Status")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("ExperienceId", "Status")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("experience_bookings", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("experience_categories", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceModerationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.HasIndex("ExperienceId", "CreatedAtUtc");

                    b.ToTable("experience_moderation_events", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "TravelerProfileId")
                        .IsUnique();

                    b.ToTable("experience_reviews", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId", "Name")
                        .IsUnique();

                    b.ToTable("experience_tags", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceVibe", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VibeId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "VibeId");

                    b.HasIndex("VibeId");

                    b.ToTable("experience_vibes", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Vibe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vibes", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Experience", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.ExperienceCategory", "Category")
                        .WithMany("Experiences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceBooking", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", "Availability")
                        .WithMany("Bookings")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Bookings")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceModerationEvent", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("ModerationHistory")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReview", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Reviews")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceTag", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Tags")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceVibe", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceVibes")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Vibe", "Vibe")
                        .WithMany("ExperienceVibes")
                        .HasForeignKey("VibeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Vibe");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Experience", b =>
                {
                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Bookings");

                    b.Navigation("ExperienceVibes");

                    b.Navigation("ModerationHistory");

                    b.Navigation("Reviews");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceCategory", b =>
                {
                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Vibe", b =>
                {
                    b.Navigation("ExperienceVibes");
                });
#pragma warning restore 612, 618
        }
    }
}
