// <auto-generated />
using System;
using Glinter.Modules.Experiences.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.Experiences.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExperiencesDbContext))]
    partial class ExperiencesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("experiences")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<int?>("Adm0Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm1Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm2Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm3Gid")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Cid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("GoogleMapsLink")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ModeratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PhoneInternational")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProviderProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int?>("Reviews")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Adm0Gid");

                    b.HasIndex("Adm1Gid");

                    b.HasIndex("Adm2Gid");

                    b.HasIndex("Adm3Gid");

                    b.HasIndex("Category");

                    b.HasIndex("Cid")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("ProviderProfileId");

                    b.HasIndex("Rating");

                    b.HasIndex("SourceType");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("experiences", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "Name")
                        .IsUnique();

                    b.ToTable("experience_amenities", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PricePerPerson")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "StartTimeUtc", "EndTimeUtc");

                    b.ToTable("experience_availability", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TravelerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("TravelerProfileId");

                    b.ToTable("experience_bookings", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceFeaturedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "Link")
                        .IsUnique();

                    b.ToTable("experience_featured_images", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "DayOfWeek", "OpensAt", "ClosesAt")
                        .IsUnique();

                    b.ToTable("experience_hours", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperiencePopularTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("integer");

                    b.Property<int>("PopularityPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "DayOfWeek", "HourOfDay")
                        .IsUnique();

                    b.ToTable("experience_popular_times", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalReviewId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SourceList")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("PublishedAtDate");

                    b.HasIndex("Rating");

                    b.HasIndex("ExperienceId", "ExternalReviewId")
                        .IsUnique();

                    b.ToTable("experience_reviews", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReviewsPerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("ExperienceId", "Rating")
                        .IsUnique();

                    b.ToTable("experience_reviews_per_rating", "experiences");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAmenity", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Amenities")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceBooking", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", "Availability")
                        .WithMany("Bookings")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Bookings")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceFeaturedImage", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("FeaturedImages")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceHour", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("Hours")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperiencePopularTime", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("PopularTimes")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReview", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("ExperienceReviews")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceReviewsPerRating", b =>
                {
                    b.HasOne("Glinter.Modules.Experiences.Domain.Entities.Experience", "Experience")
                        .WithMany("ReviewsPerRatings")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.Experience", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Bookings");

                    b.Navigation("ExperienceReviews");

                    b.Navigation("FeaturedImages");

                    b.Navigation("Hours");

                    b.Navigation("PopularTimes");

                    b.Navigation("ReviewsPerRatings");
                });

            modelBuilder.Entity("Glinter.Modules.Experiences.Domain.Entities.ExperienceAvailability", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
