<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6dd178cc-e7d7-4e5d-aad8-5420e6e7c800</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Stays\Application\Abstractions\" />
    <Folder Include="Modules\Stays\Application\Bookings\Commands\" />
    <Folder Include="Modules\Stays\Application\Bookings\Dtos\" />
    <Folder Include="Modules\Stays\Application\Bookings\Queries\" />
    <Folder Include="Modules\Stays\Application\Listings\Commands\" />
    <Folder Include="Modules\Stays\Application\Listings\Dtos\" />
    <Folder Include="Modules\Stays\Application\Listings\Queries\" />
    <Folder Include="Modules\Stays\Application\Reviews\Commands\" />
    <Folder Include="Modules\Stays\Application\Reviews\Dtos\" />
    <Folder Include="Modules\Stays\Application\Reviews\Queries\" />
    <Folder Include="Modules\Stays\Domain\Enums\" />
    <Folder Include="Modules\Stays\Domain\ValueObjects\" />
    <Folder Include="Modules\Stays\Infrastructure\DependencyInjection\" />
    <Folder Include="Modules\Stays\Infrastructure\Persistence\Repositories\" />
  </ItemGroup>

</Project>
