// <auto-generated />
using System;
using Glinter.Modules.Regions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.Regions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegionsDbContext))]
    partial class RegionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm0", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Gid"));

                    b.Property<MultiPolygon>("BoundaryGeom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("boundary_geom");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("text")
                        .HasColumnName("flag_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("NameAr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Gid");

                    b.HasIndex("BoundaryGeom")
                        .HasDatabaseName("ix_adm0_boundary_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryGeom"), "gist");

                    b.HasIndex("Pcode")
                        .IsUnique()
                        .HasDatabaseName("ix_adm0_pcode");

                    b.ToTable("adm0", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm1", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Gid"));

                    b.Property<int>("Adm0Gid")
                        .HasColumnType("integer")
                        .HasColumnName("adm0_gid");

                    b.Property<MultiPolygon>("BoundaryGeom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("boundary_geom");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("NameAr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Gid");

                    b.HasIndex("Adm0Gid");

                    b.HasIndex("BoundaryGeom")
                        .HasDatabaseName("ix_adm1_boundary_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryGeom"), "gist");

                    b.HasIndex("Pcode")
                        .IsUnique()
                        .HasDatabaseName("ix_adm1_pcode");

                    b.ToTable("adm1", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm2", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Gid"));

                    b.Property<int>("Adm1Gid")
                        .HasColumnType("integer")
                        .HasColumnName("adm1_gid");

                    b.Property<MultiPolygon>("BoundaryGeom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("boundary_geom");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("NameAr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Gid");

                    b.HasIndex("Adm1Gid");

                    b.HasIndex("BoundaryGeom")
                        .HasDatabaseName("ix_adm2_boundary_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryGeom"), "gist");

                    b.HasIndex("Pcode")
                        .IsUnique()
                        .HasDatabaseName("ix_adm2_pcode");

                    b.ToTable("adm2", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm3", b =>
                {
                    b.Property<int>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Gid"));

                    b.Property<int>("Adm2Gid")
                        .HasColumnType("integer")
                        .HasColumnName("adm2_gid");

                    b.Property<MultiPolygon>("BoundaryGeom")
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("boundary_geom");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("NameAr")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("Pcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Gid");

                    b.HasIndex("Adm2Gid");

                    b.HasIndex("BoundaryGeom")
                        .HasDatabaseName("ix_adm3_boundary_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryGeom"), "gist");

                    b.HasIndex("Pcode")
                        .IsUnique()
                        .HasDatabaseName("ix_adm3_pcode");

                    b.ToTable("adm3", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm1", b =>
                {
                    b.HasOne("Glinter.Modules.Regions.Domain.Entities.Adm0", "Country")
                        .WithMany("Governorates")
                        .HasForeignKey("Adm0Gid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm2", b =>
                {
                    b.HasOne("Glinter.Modules.Regions.Domain.Entities.Adm1", "Governorate")
                        .WithMany("Districts")
                        .HasForeignKey("Adm1Gid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm3", b =>
                {
                    b.HasOne("Glinter.Modules.Regions.Domain.Entities.Adm2", "District")
                        .WithMany("Neighbourhoods")
                        .HasForeignKey("Adm2Gid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm0", b =>
                {
                    b.Navigation("Governorates");
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm1", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Glinter.Modules.Regions.Domain.Entities.Adm2", b =>
                {
                    b.Navigation("Neighbourhoods");
                });
#pragma warning restore 612, 618
        }
    }
}
