// <auto-generated />
using System;
using Glinter.Modules.SafetyIndex.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.SafetyIndex.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SafetyIndexDbContext))]
    partial class SafetyIndexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.SafetyIndex.Domain.Entities.SafetyIndexResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adm2Gid")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HistoricalCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoricalGeneralSafetyDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("HistoricalNewsItemCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoricalScore")
                        .HasColumnType("integer");

                    b.Property<string>("HistoricalTrendingEventDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WeeklyCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeeklyGeneralSafetyDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("WeeklyNewsFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeeklyNewsItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("WeeklyNewsToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WeeklyScore")
                        .HasColumnType("integer");

                    b.Property<string>("WeeklyTrendingEventDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Adm2Gid")
                        .IsUnique();

                    b.ToTable("safety_index_results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
