// <auto-generated />
using System;
using Glinter.Modules.Stays.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.Stays.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StaysDbContext))]
    [Migration("20260628154116_AddSearchAndReportingIndexes")]
    partial class AddSearchAndReportingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.Stay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Adm3Gid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Adm3Gid");

                    b.HasIndex("IsActive", "CreatedAtUtc");

                    b.HasIndex("OwnerProfileId", "CreatedAtUtc");

                    b.HasIndex("Adm3Gid", "IsActive", "CreatedAtUtc");

                    b.HasIndex("IsActive", "Currency", "PricePerNight");

                    b.HasIndex("OwnerProfileId", "Name", "Address")
                        .IsUnique();

                    b.ToTable("stays", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Status");

                    b.HasIndex("StayId", "Status");

                    b.HasIndex("StayId", "CheckInDate", "CheckOutDate")
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.HasIndex("StayId", "TravelerProfileId", "CheckInDate", "CheckOutDate")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("stay_bookings", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StayId", "TravelerProfileId")
                        .IsUnique();

                    b.ToTable("stay_reviews", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StayId");

                    b.ToTable("stay_tags", (string)null);
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBooking", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Bookings")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReview", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Reviews")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayTag", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Tags")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.Stay", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
