// <auto-generated />
using System;
using Glinter.Modules.Stays.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Glinter.Modules.Stays.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StaysDbContext))]
    partial class StaysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stays")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.Stay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Adm0Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm1Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm2Gid")
                        .HasColumnType("integer");

                    b.Property<int?>("Adm3Gid")
                        .HasColumnType("integer");

                    b.Property<string>("Cid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("GoogleMapsLink")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("HotelOwnerProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationSummaryDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PhoneInternational")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<int?>("Reviews")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Adm0Gid");

                    b.HasIndex("Adm1Gid");

                    b.HasIndex("Adm2Gid");

                    b.HasIndex("Adm3Gid");

                    b.HasIndex("Cid")
                        .IsUnique();

                    b.HasIndex("HotelOwnerProfileId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Price");

                    b.HasIndex("Rating");

                    b.HasIndex("SourceType");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("stays", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StayId");

                    b.HasIndex("StayId", "NameAr", "NameEn")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("StayId", "NameAr", "NameEn"), false);

                    b.ToTable("stay_amenities", "stays", t =>
                        {
                            t.HasCheckConstraint("CK_stay_amenities_has_name", "NULLIF(BTRIM(\"NameAr\"), '') IS NOT NULL\r\nOR NULLIF(BTRIM(\"NameEn\"), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TravelerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StayId");

                    b.HasIndex("TravelerProfileId");

                    b.HasIndex("StayId", "CheckInDate", "CheckOutDate");

                    b.ToTable("stay_bookings", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBookingPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal?>("PriceWithTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StayId");

                    b.HasIndex("StayId", "Name", "Link")
                        .IsUnique();

                    b.ToTable("stay_booking_platforms", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StayId");

                    b.HasIndex("StayId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("stay_favorites", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StayId");

                    b.HasIndex("StayId", "Link")
                        .IsUnique();

                    b.ToTable("stay_images", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReviewId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PublishedAtDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("Platform");

                    b.HasIndex("PublishedAtDate");

                    b.HasIndex("Rating");

                    b.HasIndex("StayId");

                    b.HasIndex("StayId", "ExternalReviewId")
                        .IsUnique();

                    b.ToTable("stay_reviews", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReviewsPerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<int>("StayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StayId");

                    b.HasIndex("StayId", "Rating")
                        .IsUnique();

                    b.ToTable("stay_reviews_per_rating", "stays");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayAmenity", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Amenities")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBooking", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Bookings")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBookingPlatform", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("BookingPlatforms")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayFavorite", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayImage", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("Images")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReview", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.StayBooking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("Glinter.Modules.Stays.Domain.Entities.StayReview", "BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("StayReviews")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayReviewsPerRating", b =>
                {
                    b.HasOne("Glinter.Modules.Stays.Domain.Entities.Stay", "Stay")
                        .WithMany("ReviewsPerRatings")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.Stay", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("BookingPlatforms");

                    b.Navigation("Bookings");

                    b.Navigation("Images");

                    b.Navigation("ReviewsPerRatings");

                    b.Navigation("StayReviews");
                });

            modelBuilder.Entity("Glinter.Modules.Stays.Domain.Entities.StayBooking", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
